name: Release

on:
  push:
    branches:
      - main
      - release  # FIXME

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
      # Create/update release PR
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # Make sure we create the PR against the correct branch.
          target-branch: ${{ github.ref_name }}
          # Use a special shaka-bot access token for releases.
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          # See also settings in these files:
          manifest-file: .release-please-manifest.json
          config-file: .release-please-config.json

  # The jobs below are all conditional on a release having been created by
  # someone merging the release PR.  They all run in parallel.

  pypi:
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.release_created
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Python deps
        run: |
          sudo apt -y install twine
          python3 -m pip install -r requirements.txt
          python3 -m pip install -r optional_requirements.txt

      - name: Build modules
        run: |
          rm -rf build dist shaka_streamer.egg-info/
          rm -rf binaries/dist binaries/shaka_streamer_binaries.egg-info
          rm -f binaries/streamer_binaries/{ffmpeg-*,ffprobe-*,packager-*}
          python3 setup.py sdist bdist_wheel
          python3 binaries/build_wheels.py

      - name: Check modules
        run: |
          python3 -m twine check --strict dist/* binaries/dist/*

      - name: Publish modules
        run: |
          python3 -m twine upload --repository testpypi dist/*
          python3 -m twine upload --repository testpypi binaries/dist/*
